// skillsData.js
export const skillsData = [
  { name: "Python", value: 90 },
  { name: "SQL", value: 97 },
  { name: "Tableau", value: 97 },
  { name: "Power BI", value: 88 },
  { name: "Excel", value: 99 },
  { name: "R", value: 60 },
  { name: "Pandas", value: 80 },
  { name: "NumPy", value: 86 },
  { name: "scikit-learn", value: 75 },
  { name: "Matplotlib", value: 70 },
  { name: "Seaborn", value: 75 },
  { name: "VBA", value: 95 },
  { name: "Google Analytics", value: 80 },
  { name: "QuickBase", value: 96 },
  { name: "Domo", value: 90 },
  { name: "Metabase", value: 85 },
  { name: "AWS", value: 70 },
  { name: "Selenium", value: 95 },
  { name: "BeautifulSoup", value: 95 },
  { name: "Hadoop", value: 70 },
  { name: "Spark", value: 65 },
  { name: "GIS", value: 60 },
  { name: "Salesforce", value: 80 },
  { name: "Google Sheets", value: 98 },
  { name: "Machine Learning", value: 80 },
  { name: "Data Mining", value: 85 },
  { name: "Data Engineering", value: 70 },
  { name: "Web Scraping", value: 95 },
  { name: "Predictive Modeling", value: 80 },
  { name: "Bioinformatics", value: 65 },
  { name: "Healthcare Analytics", value: 75 }
];
